### ISSUE TITLE
Feature Request: identify SG by ID rather than name

### ISSUE THREAD

**Issue by packeteer** [erik/holepunch#1]
Rather than identifying the SG by name (I inherited a mess), it would be easier to quote the group ID.

Thanks.

**Comment by erik** [comment]
Good idea! I'll add support for this.

**Comment by erik** [comment]
Thanks for the feature request! This is now available in holepunch 0.2.0.

Let me know if you run into any problems

**Comment by packeteer** [comment]
works like a charm!

much thanks!!
