### ISSUE TITLE
Feature: Execute command instead of waiting

### ISSUE THREAD

**Issue by hoegertn** [erik/holepunch#10]
Instead of waiting for Ctrl+c I would love an option to run a subcommand and to close the ingress when this subcommand exits.

Use case: Run SSH to a host and wrap it with holepunch to open access

Proposed syntax: `holepunch -c "ssh myserver" <mySecGrpId> 22`

**Comment by erik** [comment]
This is a great idea, and one that has been asked for by a couple different people (you being the first to make a ticket 🙂). I'll work on adding this when I get some time!

Thanks for the request @hoegertn!

**Comment by erik** [comment]
Hi @hoegertn 

Just released `holepunch==0.6.0` which implements this feature!

Thanks again for the feature request and let me know if you run into any bugs!

**Comment by hoegertn** [comment]
Thanks, will try it.
