### ISSUE TITLE
Since 0.7.0 only IPv6 is added to the SG

### ISSUE THREAD

**Issue by hoegertn** [erik/holepunch#15]
Sorry for bothering again, but I upgraded to 0.7.1 for the botocore fix and now it only adds my external v6 address and I cannot connect to my servers via v4. 

I see two solutions here:
1) add both v4 and v6 to whitelist
2) add a flag to choose the IP version on the commandline

**Comment by erik** [comment]
Ah, the IP service I'm using (http://icanhazip.com/) must be giving preference to IPv6 when both are available. I'll add a flag to force IPv4 or IPv6 in such situations.

In the mean time, a hack: `holepunch --cidr $(curl -s http://ipv4.icanhazip.com/)/32 ...`

Thanks again for the bug reports! I really do appreciate the feedback 😄

**Comment by hoegertn** [comment]
Great, thanks. I really love the tool and include it in my scripts so I hit several things.

All server access is now done using a bastion host which is guarded by holepunch.

**Comment by erik** [comment]
Added `-4` and `-6` to holepunch version `0.8.0` to choose which IP version to use!

Maybe at some point I'll support adding both v4 and v6 (or arbitrarily many IP ranges) if that ends up being a useful feature to have.

Thanks again @hoegertn 👍
