### ISSUE TITLE
Add working with profiles from AWS

### ISSUE THREAD

**Issue by marcinpraczko** [erik/holepunch#5]
Would be nice to add functionallity to work with AWS profiles - like most of AWS commands are working: --profile XXX

Links:
- http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
- http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

**Comment by erik** [comment]
Good idea! Thanks for the suggestion. 

Right now you should be able to set the `AWS_PROFILE` environment variable (e.g. `AWS_PROFILE=dev holepunch --tcp ...`) but it would be convenient to make this a command line argument as well.

I'll add this feature when I get a chance

**Comment by erik** [comment]
Thanks again for the idea @marcinpraczko, I just publish holepunch version `0.4.0`, which adds support for `--profile`.

Let me know if you run into any issues!

`pip install --upgrade holepunch`

**Comment by marcinpraczko** [comment]
Great work - really big thank you for so fast reaction - well done: +1
